### ISSUE TITLE
object '.deinf' not found 

### ISSUE THREAD

**Issue by dth2** [statnet/ergm#142]
I am trying to get a simulation to run and I am getting the following error.  I have reverted to public github versions of ergm, tergm, network and statnet.common  Session info is below.

![image](https://user-images.githubusercontent.com/10469169/74560952-7b07aa80-4f1c-11ea-82af-a3388b16f84d.png)

![image](https://user-images.githubusercontent.com/10469169/74561119-db96e780-4f1c-11ea-9112-abe4f04bde6b.png)

**Comment by martinamorris** [comment]
i'm guessing .deinf is coming from either EpiModel or EpiModelHIV.   there needs to be a consistent install.stack for {EpiModel, tergmlite, EpiModelHIV}

@smjenness or @andsv2 do you have suggestions for that for `tergmlite_1.2.0`?

**Comment by smjenness** [comment]
I'm not certain that older (pre networkLite API work that Chad completed) are compatible with public github versions of the statnet packages. I would recommend updating to the latest version of tergmLite if you need to use those newer statnet packages. 

If you are needing to use the older version of tergmLite, then here is an example set of packages that work together: https://github.com/EpiModel/CombPrev/blob/master/InstallStack.R

If you are starting a new project, I recommend updating to the new set of all the packages and making any necessary updates to your EpiModelHIV code. Once tergmLite gets approved for CRAN (currently v2.1.7 is under review there) all new projects should use this new set of packages.

**Comment by krivit** [comment]
It looks like it's trying to use `ergm:::.deinf()`, which was an internal (unexported) function in `ergm`. I have since moved it to `statnet.common` under the name `deInf()`.

**Comment by krivit** [comment]
This should be fixed by updating `statnet.common` and using `deinf()`. In general, if you need to use `:::` to access an internal function of `ergm`, it's better to open a ticket asking for it to be exported.

**Comment by martinamorris** [comment]
@smjenness i can see you deleted the call to `deinf()` in `tergmLite`, https://github.com/statnet/tergmLite/commit/309b60dd5efdda4d7d4137dc82966fa48e937d3b

but i am still getting this pesky error:

```
Error in get(name, envir = asNamespace(pkg), inherits = FALSE) : 
  object '.deinf' not found
```

With the most up-to-date install stack:

```
 package        * version     date       lib source                                 
 ARTnet           2.0.0       2020-02-13 [1] Github (epimodel/ARTnet@f32ff8f)       
 ARTnetData       1.1         2020-02-12 [1] Github (epimodel/ARTnetData@d5423b2)   
 EpiABC           1.0         2020-02-01 [2] Github (EpiModel/EpiABC@c32ecb6)       
 EpiModel       * 1.8.0       2020-02-24 [1] Github (statnet/EpiModel@1a609be)      
 EpiModelHIV    * 1.5.0       2020-02-24 [1] Github (EpiModel/EpiModelHIV-p@6102b0d)
 EpiModelHPC    * 2.1.0       2020-02-24 [1] Github (statnet/EpiModelHPC@257bbf3)   
 ergm           * 3.10.4-5400 2020-02-24 [1] Github (statnet/ergm@aeac0ce)          
 network        * 1.17.0-411  2020-02-24 [1] Github (statnet/network@87f47bb)       
 networkDynamic * 0.10.1      2020-02-24 [1] Github (statnet/networkDynamic@157dede)
 statnet.common   4.4.0-258   2020-02-24 [1] Github (statnet/statnet.common@838c389)
 tergm          * 3.6.2-1685  2020-02-24 [1] Github (statnet/tergm@535f2d6)         
 tergmLite      * 2.1.7       2020-02-24 [1] Github (statnet/tergmLite@b989564)  
```
I can't find the string `deinf` anywhere in the EpiModel related code now.  Do you have any idea why this might be happening?

**Comment by krivit** [comment]
Huh... It looks like it's in a release, as well. How the heck this get past CRAN?

**Comment by martinamorris** [comment]
lmk when it's fixed, thx.

**Comment by krivit** [comment]
Forgot to tag the commit, but 616fdfd24ed292251e99c9aac7c4b62adcaab955 should fix it.

**Comment by martinamorris** [comment]
yep, works like a charm, thx Pavel
