### ISSUE TITLE
predict.ergm() fails on models with offsets

### ISSUE THREAD

**Issue by mbojan** [statnet/ergm#172]
E.g.:

```r
data("faux.mesa.high")
summary(faux.mesa.high ~ edges + offset(nodematch("Sex", diff=FALSE)))
##              edges offset(nodematch.Sex) 
##                203                   132 
fit <- ergm(faux.mesa.high ~ edges +  offset(nodematch("Sex", diff=FALSE)), offset.coef = 2)
predict(fit)
## Error in predict.formula(object = object$formula, theta = ergm.eta(object$coef,  : 
##  length(theta) == (ncol(predmat) - 2) is not TRUE
```

**Comment by mbojan** [comment]
It seems that `ergmMPLE()` returns results of `ergm.pl()` using its `xmat` element which does not contain offset columns. Should this rather use the `xmat.full` element in the call to `switch()` at the end? 
https://github.com/statnet/ergm/blob/552726ca3b03dbfdc8208c99eb2634b6ddfd83e3/R/ergmMPLE.R#L171

@krivit ?

**Comment by krivit** [comment]
I think so. On that note, `ergmMPLE()` should probably have an `offset.coef=` argument as `ergm` does.

**Comment by martinamorris** [comment]
There's a bit of urgency to this, as I need it for WHAMP diagnostics.  Is it difficult or time consuming to implement?  Likely to happen for 3.11?  Either way, lmk, and I'll reorganize my work queue accordingly.

**Comment by mbojan** [comment]
I'm on it @martinamorris .

**Comment by mbojan** [comment]
> I think so. On that note, `ergmMPLE()` should probably have an `offset.coef=` argument as `ergm` does.

@krivit, it actually "has it" -- it is passed to `ergm()` if `ergmMPLE(output="fit")`, e.g.:

```r
data("faux.mesa.high")
ergmMPLE(
  faux.mesa.high ~ edges + offset(nodematch("Sex", diff=FALSE)),
  output = "fit",
  offset.coef = 2
)
## Starting maximum pseudolikelihood estimation (MPLE):
## Evaluating the predictor and response matrix.
## Maximizing the pseudolikelihood.
## Finished MPLE.
## Stopping at the initial estimate.
## Evaluating log-likelihood at the estimate. 
## 
## Call:
## ergm(formula = formula, constraints = constraints, offset.coef = 2, 
##     estimate = "MPLE", control = control, verbose = verbose)
## 
## 
## MPLE Coefficients:
##                 edges  offset(nodematch.Sex)  
##                 -6.05                   2.00  
```

At the same time it is not needed if `output != "fit"` (right?).

**Comment by krivit** [comment]
Ah, the good old dots... It looks like a search-and-replace.

**Comment by mbojan** [comment]
Thx @krivit , now I have your patch on master parallel to my edits on a branch... :)

**Comment by mbojan** [comment]
I'll close when I finish the test.

**Comment by mbojan** [comment]
Done.

**Comment by martinamorris** [comment]
Thank you!!!

**Comment by martinamorris** [comment]
I'm still getting the error I got before.  This model has a total of 4 offsets, the error is complaining about a discrepancy of 2, so I'm not sure it's offset related.

```
> sessioninfo::package_info(pkgs = c("network","statnet.common","ergm",
+                                    "ergm.ego"),
+                           dependencies = FALSE)
 package        * version     date       lib source                                 
 ergm           * 3.11.0-5735 2020-09-29 [1] Github (statnet/ergm@e032a62)          
 ergm.ego       * 0.6.0-471   2020-09-29 [1] Github (statnet/ergm.ego@ae8ecb3)      
 network        * 1.17.0-569  2020-09-29 [1] Github (statnet/network@90c8d59)       
 statnet.common   4.4.0-294   2020-09-29 [1] Github (statnet/statnet.common@68e2c4c)

[1] /homes/morrism/R/release-library
[2] /homes/morrism/R/x86_64-pc-linux-gnu-library/4.0
[3] /usr/lib/R/library
[4] /net/debian10/lib/R/site-library

>  summary(fit_casl)
Call:
ergm(formula = ergm.formula, offset.coef = ergm.offset.coef, 
    target.stats = m, eval.loglik = FALSE, control = control$ergm.control)

Iterations:  3 out of 20 

Monte Carlo MLE Results:
                                Estimate Std. Error MCMC % z value Pr(>|z|)    
offset(netsize.adj)           -9.6156721  0.0000000      0    -Inf  < 1e-04 ***
edges                         -3.8147713  0.8834310      0  -4.318  < 1e-04 ***
nodecov.age                    0.0713855  0.0179811      0   3.970  < 1e-04 ***
nodecov.age^2                 -0.0008345  0.0002145      0  -3.890 0.000100 ***
nodecov.age<16                -0.7796414  1.0568075      0  -0.738 0.460677    
nodefactor.race.B              0.9571486  0.1833278      0   5.221  < 1e-04 ***
nodefactor.race.H              0.8915789  0.2664661      0   3.346 0.000820 ***
nodefactor.region.EasternWA   -0.7966291  0.4682810      0  -1.701 0.088910 .  
nodefactor.region.WesternWA   -0.9529215  0.5193409      0  -1.835 0.066525 .  
absdiff.sqrt.age              -0.5659757  0.0564882      0 -10.019  < 1e-04 ***
nodematch.race.B               0.1324029  0.5101171      0   0.260 0.795208    
nodematch.race.H              -0.4434389  0.4126599      0  -1.075 0.282560    
nodematch.race.O               0.9827980  0.2639918      0   3.723 0.000197 ***
nodematch.region.EasternWA     4.5932011  0.5081487      0   9.039  < 1e-04 ***
nodematch.region.King          1.4430628  0.5701671      0   2.531 0.011376 *  
nodematch.region.WesternWA     3.8970940  0.5094960      0   7.649  < 1e-04 ***
concurrent                    -0.1692039  0.1340484      0  -1.262 0.206855    
nodefactor.deg.main>0.TRUE    -0.2872258  0.1383606      0  -2.076 0.037901 *  
offset(nodematch.role.type.0)       -Inf  0.0000000      0    -Inf  < 1e-04 ***
offset(nodematch.role.type.1)       -Inf  0.0000000      0    -Inf  < 1e-04 ***
offset(nodecov.age>66)              -Inf  0.0000000      0    -Inf  < 1e-04 ***
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1


 The following terms are fixed by offset and are not estimated:
  offset(netsize.adj) offset(nodematch.role.type.0) offset(nodematch.role.type.1) offset(nodecov.age>66) 

> pnet <- predict(fit_casl) # data frame
Error in predict.formula(frm, theta = th, ...) : 
  length(theta) == (ncol(predmat) - 2) is not TRUE
In addition: Warning message:
In ergm.pl(nw, fd, model, verbose = verbose, control = control,  :
  Too many unique dyads. MPLE is approximate, and MPLE standard errors are suspect.
```

**Comment by mbojan** [comment]
Argh... A non-finite offset. Let me check.

**Comment by martinamorris** [comment]
Here's a reprex:

```
data("faux.magnolia.high")
fmhego <- as.egodata(faux.magnolia.high)

fit <- ergm.ego(fmhego ~ edges 
                + nodefactor("Grade")
                + nodematch("Grade", diff=T)
                + offset(nodematch("Sex",
                                   diff = TRUE,
                                   levels = c(1, 2))),
                offset.coef = rep(-Inf, 2))

pnet <- predict(fit) # data frame
```

**Comment by martinamorris** [comment]
I can change the offsets to a large negative number for now.  But it would be good to have the -Inf option, as we use that a lot.

**Comment by mbojan** [comment]
Does it work with large but finite offset coefs?

**Comment by martinamorris** [comment]
sadly, no:

```
data("faux.magnolia.high")
fmhego <- as.egodata(faux.magnolia.high)

fit <- ergm.ego(fmhego ~ edges
                + nodefactor("Grade")
                + nodematch("Grade")
                + offset(nodematch("Sex")),
                offset.coef = (-10))

pnet <- predict(fit) # data frame

#####################3

> summary(fit)
Call:
ergm(formula = ergm.formula, offset.coef = ergm.offset.coef, 
    target.stats = m, eval.loglik = FALSE, control = control$ergm.control)

Iterations:  2 out of 20 

Monte Carlo MLE Results:
                       Estimate Std. Error MCMC % z value Pr(>|z|)    
offset(netsize.adj)    -7.28688    0.00000      0    -Inf   <1e-04 ***
edges                   0.98557    0.02809      0   35.09   <1e-04 ***
offset(nodematch.Sex) -10.00000    0.00000      0    -Inf   <1e-04 ***
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1


 The following terms are fixed by offset and are not estimated:
  offset(netsize.adj) offset(nodematch.Sex) 

> pnet <- predict(fit) # data frame
Error in predict.formula(frm, theta = th, ...) : 
  length(theta) == (ncol(predmat) - 2) is not TRUE
In addition: Warning message:
In ergm.pl(nw, fd, model, verbose = verbose, control = control,  :
  Too many unique dyads. MPLE is approximate, and MPLE standard errors are suspect.
```

and yes, i did have an error in the offset specification of this reprex before.  cut and pasted too quickly...

**Comment by chad-klumb** [comment]
Just guessing atm, but perhaps this line in the `ergm.ego` method is a problem:

https://github.com/statnet/ergm.ego/blob/04473d4f931b6c43f3c2bff5c1e0cb9718e0e07f/R/predict.ergmego.R#L17

This drops all offsets, while (I'm assuming) the intent was to drop only the `netsize.adj` offset.

cf. the `ergm` method

https://github.com/statnet/ergm/blob/e032a627107983d27c7f530a36312c71bf5aa95a/R/predict.ergm.R#L138

which does not drop offsets (and of course there is no `netsize.adj` offset to drop in that case).

**Comment by chad-klumb** [comment]
Is `netsize.adj` always the first coefficient in the `ergm.ego` fit?  This line seems to suggest it will be,

https://github.com/statnet/ergm.ego/blob/04473d4f931b6c43f3c2bff5c1e0cb9718e0e07f/R/ergm.ego.R#L214

in which case we could simply drop the first coefficient rather than all the offsets.

**Comment by martinamorris** [comment]
Yes.

**Comment by chad-klumb** [comment]
I did quickly test that approach and it seemed to work in that the `predict` call ran without error.

**Comment by martinamorris** [comment]
@chad-klumb Great! Would you please submit a PR for this?  @mbojan  has written some tests that he can follow up with.

**Comment by chad-klumb** [comment]
PR has been made

**Comment by mbojan** [comment]
We still have the problem with non-finite offset coefs:

```r
  data("faux.mesa.high")
  fit <- ergm(
    faux.mesa.high ~ edges 
    + nodefactor("Grade")
    + nodematch("Grade", diff=T)
    + offset(nodematch("Sex", diff = TRUE, levels = c(1, 2))),
    offset.coef = rep(-Inf, 2)
  )
  expect_silent(
    p <- predict(fit)
  )
  expect_true(
    all(is.finite(p$p))
  )
## Error: all(is.finite(p$p)) isn't true.
head(p)
##   tail head   p
## 1  116  136 NaN
## 2  114  136 NaN
## 3  126  168 NaN
## 4    9  184 NaN
## 5   53   58 NaN
## 6   81  104 NaN
```

I naively assumed that we can simply multiply the model matrix by the vector of coefficients (including offsets). Whats should be a convention here? If offset column is 0 then have 0 in the result if offset coef is Inf?
